// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK-BaMqUzNe-WC-kqn8hb8mfq4WvJCfvI',
    appId: '1:233952460253:web:80a81c993a2c94da8e0a34',
    messagingSenderId: '233952460253',
    projectId: 'cn-auth-1a28f',
    authDomain: 'cn-auth-1a28f.firebaseapp.com',
    storageBucket: 'cn-auth-1a28f.appspot.com',
    measurementId: 'G-7KLZRR23G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBypjUJl2SWnxyGOT17gVb1KaSmMplnAoU',
    appId: '1:233952460253:android:728f242ca51b70a18e0a34',
    messagingSenderId: '233952460253',
    projectId: 'cn-auth-1a28f',
    storageBucket: 'cn-auth-1a28f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFdCFjvtrDGAvCXQ_t59OmRoVWI3OUkco',
    appId: '1:233952460253:ios:e06d50428b31cbe88e0a34',
    messagingSenderId: '233952460253',
    projectId: 'cn-auth-1a28f',
    storageBucket: 'cn-auth-1a28f.appspot.com',
    iosClientId: '233952460253-vl5jcckm8808j8nl9nl6msgko6nebq6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.cnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFdCFjvtrDGAvCXQ_t59OmRoVWI3OUkco',
    appId: '1:233952460253:ios:e06d50428b31cbe88e0a34',
    messagingSenderId: '233952460253',
    projectId: 'cn-auth-1a28f',
    storageBucket: 'cn-auth-1a28f.appspot.com',
    iosClientId: '233952460253-vl5jcckm8808j8nl9nl6msgko6nebq6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.cnApp',
  );
}
